# Generated by Django 3.0.9 on 2020-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='file',
            name='description_hr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='file',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='file',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='file',
            name='name_hr',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='file',
            name='name_it',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='image',
            name='default_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default alt text'),
        ),
        migrations.AddField(
            model_name='image',
            name='default_alt_text_hr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default alt text'),
        ),
        migrations.AddField(
            model_name='image',
            name='default_alt_text_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default alt text'),
        ),
        migrations.AddField(
            model_name='image',
            name='default_caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default caption'),
        ),
        migrations.AddField(
            model_name='image',
            name='default_caption_hr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default caption'),
        ),
        migrations.AddField(
            model_name='image',
            name='default_caption_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default caption'),
        ),
    ]
